### ISSUE TITLE
Facebook login

### ISSUE THREAD

**Issue by nerdy-sam** [nus-mtp/worldscope#86]
Found worldscope on fdriod, concept looks very neat, just curious why Facebook login is required? All the best!

**Comment by ndt93** [comment]
Thank mitzip for your interests!

We were trying to make an open source clone of Periscope, which is integrated with Twitter; so we thought of using Facebook as an similar alternative that could support similar features such as sharing live streams, adding friends using Facebook friends list etc.

Login independent of Facebook should have been supported too. However we are doing this under the constraint of a semester university project and decided to implement higher priority requirements first i.e. social media integration.

**Comment by nerdy-sam** [comment]
Completely understand, keep it up, this sounds like a good project!
