### ISSUE TITLE
Stream preview is streched

### ISSUE THREAD

**Issue by MhtSuthar** [nus-mtp/worldscope#92]
Hi, 
My Android devices is supporting 1280x720(Also tried different resolution) resolution and i am streaming with that resolution. But on while viewing preview it is not proper and it's streching.

**Comment by ndt93** [comment]
Hi @MhtSuthar. Yes, it a problem that we are aware of. However, since we are no longer maintaining this project, this bug might not be fixed any time soon.

This might be fixed by performing additional video processing on the client or adding a custom extension on top of Wowza's transcoder.

**Comment by MhtSuthar** [comment]
Hi @ndt93, i am able to make video stream preview proper. I don't have control of Wowza Stream Engine but i made it work from client side, I did used FFMpegFrameFilter with proper pad filter and changed FFMpegFrameRecorder's image height and width (swaping it for portrait mode). 
Thanks for your hint . :-)

**Comment by ndt93** [comment]
@MhtSuthar That's great. You're welcome.

**Comment by MhtSuthar** [comment]
Hi@ndt93 , Which functionality is used for chatting , I want to start streaming with chat  , Can you please suggest how can I achieve this ?

**Comment by ndt93** [comment]
Hi @MhtSuthar,

We use `socket.io` to provide the chat service in a separate _Application Server_. The `socket.io` site should provide a simple example. Most of the code should be in `/app_server/app/adapters/socket/`.

The existing code is still pretty simplistic. Examples of thing needed to be done are synchronised message id between the client and the server to prevent messages lost, using a separate NoSQL database for the chat service, in memory message queues caches, messages flow control etc.

You can also choose to use an existing industry standard system like [ejabberd](https://www.ejabberd.im) or protocol like [MQTT](http://mqtt.org)

**Comment by nigez** [comment]
Hi,
I want to know how to use media server !  i need a documentation please ...

**Comment by ndt93** [comment]
@nigez Hi nigez, the media server is simply a Wowza streaming engine running independently. The [contributing guide](https://github.com/nus-mtp/worldscope/blob/master/media_server/CONTRIBUTING.md) points to some links for Wowza's documentations and forum. You will need to sign up for a developer license of the streaming engine and follow their guides to set it up.

The code in our `media_server` directory is a Wowza extension module that exposes APIs and creates hooks to other servers for controls and authentication.

**Comment by nigez** [comment]
@ndt93 Thank you for your reply, your project contains three part a mobile client that I have run on my smartphone and I do the authentication by facebook and the second part is the server application app_server ! I do the local execution and database Is to create, so for wowza I create a test account and I installed wowza streaming manager but normally we must integrate the third part media_server  with wowza to see the video stream comes from smartphone !!  How i can integrate this java + nginx module with wowza and make it functional ? 
Because I also want to control the streaming by authentication.

**Comment by ndt93** [comment]
@nigez I'm not sure by third party media server and nginx you are referring to the nginx+rtmp streaming server. If that's the case, the nginx+rtmp is independent from Wowza and you could provide some hooks in the nginx config file to authenticate with your app_server before a stream is published.

As for the Java extension module in our repository, it's exclusively for Wowza. I don't remember all the details but you can refer to various guides from Wowza, particular on Server modules and Http Provider modules.
