### ISSUE TITLE
How to use it in Ubuntu?

### ISSUE THREAD

**Issue by huangwwmm** [nus-mtp/worldscope#94]

**Comment by ndt93** [comment]
Hi @huangwwmm,

You can refer to the `app_server/README.md`, `app_server/CONTRIBUTING.md` and `media_server/CONTRIBUTING.md` for more information on setting up the servers. The Android client is in `client/android`. The top-level README.md describes the purposes of those servers.

The application server is a NodeJS program and the media server is a Wowza streaming engine running on JVM. We've deployed to Ubuntu servers for development and production so those should work well there.
